// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5C0_oBAiaQn0f-MoFq-_XQ3HGqIwaZWU',
    appId: '1:446378717858:android:b4c9ee4d935dcbc2ffddfb',
    messagingSenderId: '446378717858',
    projectId: 'fetch-d77c3',
    databaseURL: 'https://fetch-d77c3-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fetch-d77c3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDB7ROdztIh57WTMaaHoIiFR9Oe1zg1Flo',
    appId: '1:446378717858:ios:dc8f26ede3e71d69ffddfb',
    messagingSenderId: '446378717858',
    projectId: 'fetch-d77c3',
    databaseURL: 'https://fetch-d77c3-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fetch-d77c3.appspot.com',
    iosClientId: '446378717858-isehqro2a169i3563truuhktqr94dqht.apps.googleusercontent.com',
    iosBundleId: 'com.roseikteam1.fetch',
  );
}
